# Generated by Django 4.2.2 on 2023-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
