# Generated by Django 4.2.2 on 2023-06-28 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_overtime_end_alter_overtime_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='end',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='start',
        ),
        migrations.AddField(
            model_name='overtime',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='overtime',
            name='end_time',
            field=models.TimeField(default=datetime.time(16, 30)),
        ),
        migrations.AddField(
            model_name='overtime',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='overtime',
            name='start_time',
            field=models.TimeField(default=datetime.time(16, 30)),
        ),
    ]
