# Generated by Django 4.2.2 on 2023-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_overtime_end_remove_overtime_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
