# Generated by Django 4.2.2 on 2023-06-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_overtime_hourly_rate_alter_overtime_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='multiplier',
            field=models.DecimalField(choices=[(1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0')], decimal_places=2, default=1.5, max_digits=10),
        ),
    ]
