# Generated by Django 4.2.2 on 2023-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_overtime_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
