# Generated by Django 4.2.2 on 2023-06-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_overtime_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
